name: Docker Image CI
on:
  push:
    branches: [master,action]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: palashpaul/node-test:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}